### ISSUE TITLE
Permissions to push a new branch

### ISSUE THREAD

**Issue by Stephanevg** [gravejester/Communary.ConsoleExtensions#1]
HI Ovind,

I created a branch that I wanted to push tonight. I get a error message saying i dont ahve enough rights to push to this repository.

Greetz

**Comment by gravejester** [comment]
Hi Stéphane, that's odd. Let's see if we can get it sorted out :)

**Comment by gravejester** [comment]
hm.. checked the permissions and can't see what might cause this. I haven't set any particular settings regarding this, it's all defaults. How are you doing this? Have you cloned the repo locally, created a new branch and are trying to push it back to this?

**Comment by Stephanevg** [comment]
Hi Oyvind,

Yeah, that is exactly what I did:
1) cloned the repository locally
2) created a branch
3) did the changes
4) attempted to sync the changes up

**Comment by gravejester** [comment]
I'm not sure, but try to fork the repo first, that way you have a copy of the repo in your account. If you clone this locally, do the changes, sync back up and lastly create a pull request against my repo. That should work. I hope :)

**Comment by Stephanevg** [comment]
Yeah, that looks better like that. 
I just did the PR.

**Comment by gravejester** [comment]
Nice, see it. I'll close this issue, and review your PR :)
